-- Baseline do schema, fiel as entidades JPA atuais.
-- Em banco ja existente (criado pelo ddl-auto=update), esta migracao e PULADA
-- via baseline-on-migrate; em banco novo/CI, ela cria o schema do zero.

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    email    VARCHAR(255) NOT NULL UNIQUE,
    phone    VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE accounts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255),
    type    VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id)
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    type        VARCHAR(255) NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    budget_type VARCHAR(255) NOT NULL
);

CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    value       NUMERIC(19, 2) NOT NULL,
    date        DATE NOT NULL,
    account_id  BIGINT NOT NULL REFERENCES accounts (id),
    category_id BIGINT NOT NULL REFERENCES categories (id),
    type        VARCHAR(255) NOT NULL
);
